### ISSUE TITLE
如何实现动态改变进度条

### ISSUE THREAD

**Issue by zhaohao007** [Jakemesdg/CustomCircleProgressBar#1]
进度总是随着数据下载的结果不断增加，这个动画效果如何实现？

**Comment by 24Kshign** [comment]
一个道理，你知道总的下载量和当前已经下载好的量，动态给进度条设置进度就好了

**Comment by 24Kshign** [comment]
> 进度总是随着数据下载的结果不断增加，这个动画效果如何实现？

一个道理，你知道总的下载量和当前已经下载好的量，动态给进度条设置进度就好了
